export const projectId = import.meta.env.SANITY_STUDIO_PROJECT_ID || ''
export const dataset = import.meta.env.SANITY_STUDIO_DATASET || ''
export const apiVersion = import.meta.env.SANITY_STUDIO_API_VERSION || '2023-01-01'
export const previewToken = import.meta.env.SANITY_STUDIO_PREVIEW_TOKEN || ''
export const revalidateSecret = import.meta.env.SANITY_STUDIO_REVALIDATE_SECRET || ''